#!groovy

pipeline {
  agent none
  stages {
    stage('Maven compile clean install') {
     agent {
      docker {
       image 'maven:3.5.0'
      }
     }
     steps {
       sh 'mvn compile'
     }
    }
	stage('Docker Build spring-boot') {
      agent any
      steps {
        sh 'docker build -t demo-1:latest .'
      }
	
    }
	
   }
  }
